[versions]
multimod = "0.1.5-SNAPSHOT"

minecraft = "1.21.1"
neoform = "20240808.144430"
parchment = "2024.11.17"

minecraft-supported-fabric = ">=1.21 <=1.21.1"
minecraft-supported-neoforge = "[1.21,1.21.1]"

fabric-api = "0.116.6+1.21.1"
fabric-permissions-api = "0.3.3"
fabric-modmenu = "11.0.3"

neoforge = "21.1.209"
supported-neoforge = "[21.1,)"

minecraft-release = "1.21,1.21.1"

[libraries]
minecraft = {group = "com.mojang", name = "minecraft", version.ref = "minecraft"}
parchment = {group = "org.parchmentmc.data", name = "parchment-1.21.1", version.ref = "parchment"}
fabric-api = {group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api"}
fabric-permissions-api = {group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions-api"}
fabric-modmenu = {group = "com.terraformersmc", name = "modmenu", version.ref = "fabric-modmenu"}

[plugins]
multimod = {id = "xyz.eclipseisoffline.multimod", version.ref = "multimod"}
