[versions]
multimod = "0.1.2-SNAPSHOT"

minecraft = "1.21.9"
neoform = "20250930.151910"
parchment = "2025.09.14"

minecraft-supported-fabric = "1.21.9"
minecraft-supported-neoforge = "[1.21.9]"

fabric-api = "0.134.0+1.21.9"
fabric-permissions-api = "0.4.1"
fabric-modmenu = "16.0.0-rc.1"

neoforge = "21.9.11-beta"
supported-neoforge = "[21.9,)"

minecraft-release = "1.21.9"

[libraries]
minecraft = {group = "com.mojang", name = "minecraft", version.ref = "minecraft"}
parchment = {group = "org.parchmentmc.data", name = "parchment-1.21.8", version.ref = "parchment"}
fabric-api = {group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api"}
fabric-permissions-api = {group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions-api"}
fabric-modmenu = {group = "com.terraformersmc", name = "modmenu", version.ref = "fabric-modmenu"}

[plugins]
multimod = {id = "xyz.eclipseisoffline.multimod", version.ref = "multimod"}
